version: '3.8'


services:
  postgres_db:
    image: postgres
    container_name: postgres_database_for_forum
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_config:/etc/postgresql

  backend:
    build:
      context: .
    container_name: backend_for_forum
    depends_on:
      - postgres_db
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - .env

volumes:
  postgres:
  postgres_config: