# Generated by Django 4.2.5 on 2023-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0005_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, editable=False, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views_cnt',
            field=models.IntegerField(default=0, editable=False, verbose_name='Просмотры'),
        ),
    ]
