# Generated by Django 4.2.5 on 2023-10-03 15:42

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0012_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(max_length=3000, verbose_name='Текст'),
        ),
    ]
