# Generated by Django 4.2.5 on 2023-10-03 16:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0013_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(max_length=3000, verbose_name='Текст'),
        ),
    ]
