# Generated by Django 4.2.5 on 2023-10-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0016_activityname'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='action_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum_app.activityname', verbose_name='Имя события'),
            preserve_default=False,
        ),
    ]
