# Generated by Django 4.2.6 on 2023-10-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0017_useractivity_action_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descr',
        ),
    ]
